### ISSUE TITLE
[시즌1] 영두의 TODO 리스트

### ISSUE THREAD

**Issue by woo0doo** [wonseok2877/CS-study#131]
- [ ] [language] SOLID
- [ ] [design pattern] 팩토리 메소드
- [ ] [design pattern] 싱글톤
- [ ] [database] 트랜잭션 + 정규화? 이건 양 보고 결정
