### ISSUE TITLE
[시즌1] 성욱이의 TODO 리스트

### ISSUE THREAD

**Issue by hs1430** [wonseok2877/CS-study#134]
- [ ]  [design pattern] 싱글톤 패턴
- [ ]  [design pattern] 팩토리 패턴
- [ ]  [design pattern] 전략 패턴
- [ ]  [design pattern] solid
- [ ]  [design pattern] oop
- [ ] [information_security] block chain
