### ISSUE TITLE
[시즌1] 진욱의 TODO 리스트

### ISSUE THREAD

**Issue by jinukeu** [wonseok2877/CS-study#135]
- [ ]  [design pattern] factory pattern
- [ ]  [operation system] 교착 상태
- [ ]  [design pattern] observe pattern
- [ ]  [operation_system] 페이지 교체 알고리즘
- [ ]  [operation_system] cpu 스케줄링
- [ ]  [network] RESTful API
- [ ]  [software engineering] 함수형 프로그래밍
- [ ]  [software engineering] reactive programming
- [ ]  [software engineering] oop
- [ ]  [design pattern] solid
- [ ]  [design pattern] 전략 패턴
