### ISSUE TITLE
[시즌1] 원석의 TODO 리스트

### ISSUE THREAD

**Issue by wonseok2877** [wonseok2877/CS-study#136]
- [ ] [network] OSI 7계층
- [ ] [network] TCP 3-way-handshake & 4-way-handshake
- [ ] [network] TCP vs UDP
- [ ] [spring] IoC (제어의 역전)
- [ ] [spring] Entity 설계 (DB ERD와 연결지어서!)
